### GET request to example server
GET http://localhost:8080

###
GET http://localhost:8080/api/v1/software-engineers/1
# URL must exaclty match the base endpoint in the controller
###
POST http://localhost:8080/api/v1/software-engineers
Content-Type: application/json

{
  "name": "Minkyu",
  "techStack": "java, python, spring"
}

###
POST http://localhost:8080/api/v1/software-engineers
Content-Type: application/json

{
  "name": "Sultan",
  "techStack": "java, python, spring"
}